import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <nav style={{display:"flex", gap:"16px", padding:"12px 20px", borderBottom:"1px solid #333"}}>
    <a href="/coach" style={{color:"#4ade80"}}>🏋️ トレーニングメニュー</a>
    <a href="/fitness-test" style={{color:"#4ade80"}}>🥇 体力検定診断</a>
    <a href="/weight-log" style={{color:"#4ade80"}}>⚖️ 戦闘重量ログ</a>
  </nav>
  {children}
</body>
    </html>
  );
}
 
// update
